//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add more than batch limit:.
        /// </summary>
        internal static string BatchLimitError {
            get {
                return ResourceManager.GetString("BatchLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error occured..
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No points provided for batch addition..
        /// </summary>
        internal static string EmptyBatchError {
            get {
                return ResourceManager.GetString("EmptyBatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string ExceptionError {
            get {
                return ResourceManager.GetString("ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature added successfully.
        /// </summary>
        internal static string FeatureAdded {
            get {
                return ResourceManager.GetString("FeatureAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature deleted successfully..
        /// </summary>
        internal static string FeatureDeleted {
            get {
                return ResourceManager.GetString("FeatureDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not found!.
        /// </summary>
        internal static string FeatureNotFound {
            get {
                return ResourceManager.GetString("FeatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features added successfully..
        /// </summary>
        internal static string FeaturesAdded {
            get {
                return ResourceManager.GetString("FeaturesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features not found!.
        /// </summary>
        internal static string FeaturesNotFound {
            get {
                return ResourceManager.GetString("FeaturesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature updated successfully..
        /// </summary>
        internal static string FeatureUpdated {
            get {
                return ResourceManager.GetString("FeatureUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature retrieved successfully.
        /// </summary>
        internal static string GetFeature {
            get {
                return ResourceManager.GetString("GetFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features retrieved successfully.
        /// </summary>
        internal static string GetFeatures {
            get {
                return ResourceManager.GetString("GetFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and WKT cannot be null.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WKT format.
        /// </summary>
        internal static string InvalidWKT {
            get {
                return ResourceManager.GetString("InvalidWKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be greater than 0..
        /// </summary>
        internal static string PageNumberError {
            get {
                return ResourceManager.GetString("PageNumberError", resourceCulture);
            }
        }
    }
}
